#!/bin/bash

# Define the regex for branch naming convention
BRANCH_REGEX="^(feature|bugfix|hotfix|release|dev|setup|base|refactor|story)\/[a-zA-Z0-9._-]+$"

# Get the current branch name
BRANCH_NAME=$(git symbolic-ref --short HEAD)

# Run testing
pnpm run test


# TODO: Remove temporary branch main 
# Allow branch main for temporary
if [[ ! $BRANCH_NAME =~ $BRANCH_REGEX && $BRANCH_NAME != "main" ]]; then
    echo "Error: Branch name '$BRANCH_NAME' does not follow the naming convention."
    echo "Please use one of the following prefixes: feature/, bugfix/, hotfix/, release/, dev/, setup/, base/, refactor/, story/"
    exit 1
fi